# Generated by Django 4.0.3 on 2022-03-14 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('videoCount', models.PositiveSmallIntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
                'db_table': 'Kategori',
            },
        ),
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=300, null=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('bottomDescription', models.TextField()),
                ('videoCount', models.PositiveSmallIntegerField(default=0)),
                ('price', models.PositiveSmallIntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='Admin.categorymodel')),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
                'db_table': 'Kurs',
            },
        ),
        migrations.CreateModel(
            name='courseSessionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='Admin.coursemodel')),
            ],
            options={
                'verbose_name': 'Kurs_Bolumleri',
                'verbose_name_plural': 'Kurs_Bolumleri',
                'db_table': 'Kurs_Bolumleri',
            },
        ),
        migrations.CreateModel(
            name='IletisimModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=100)),
                ('mesaj', models.TextField()),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('okundu_bilgisi', models.CharField(default='okunmadı', max_length=30)),
            ],
            options={
                'verbose_name': 'İletişim',
                'verbose_name_plural': 'İletişim',
                'db_table': 'iletisim',
            },
        ),
        migrations.CreateModel(
            name='topMenuModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=150, null=True)),
                ('userType', models.CharField(blank=True, max_length=100, null=True)),
                ('menuType', models.CharField(blank=True, default='Üst Menü', max_length=100, null=True)),
                ('menuSira', models.SmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Üst Menü',
                'verbose_name_plural': 'Üst Menüler',
                'db_table': 'topMenuModel',
            },
        ),
        migrations.CreateModel(
            name='whatWillYouLearnModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatWillYouLearns', to='Admin.coursemodel')),
            ],
            options={
                'verbose_name': 'Ogrenecekleriniz',
                'verbose_name_plural': 'Ogrenecekleriniz',
                'db_table': 'Ogrenecekleriniz',
            },
        ),
        migrations.CreateModel(
            name='courseSessionVideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('url', models.CharField(max_length=300)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('courseSession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='Admin.coursesessionmodel')),
            ],
            options={
                'verbose_name': 'Kurs_Bolum_Videosu',
                'verbose_name_plural': 'Kurs_Bolum_Videolari',
                'db_table': 'Kurs_Bolum_Video',
            },
        ),
        migrations.CreateModel(
            name='courseFeaturesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='Admin.coursemodel')),
            ],
            options={
                'verbose_name': 'Kurs_Ozellikleri',
                'verbose_name_plural': 'Kurs_Ozellikleri',
                'db_table': 'Kurs_Ozellikleri',
            },
        ),
        migrations.CreateModel(
            name='bottomMenuModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=150, null=True)),
                ('userType', models.CharField(blank=True, max_length=100, null=True)),
                ('menuType', models.CharField(blank=True, default='Alt Menü', max_length=100, null=True)),
                ('menuSira', models.SmallIntegerField(default=0)),
                ('topMenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottomMenus', to='Admin.topmenumodel')),
            ],
            options={
                'verbose_name': 'Alt Menü',
                'verbose_name_plural': 'Alt Menüler',
                'db_table': 'bottomMenuModel',
            },
        ),
    ]
