# Generated by Django 4.0.3 on 2022-04-24 16:53

import autoslug.fields
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appointmentAdminModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, max_length=250, null=True)),
                ('starting_time', models.TimeField(blank=True, max_length=250, null=True)),
                ('finishing_time', models.TimeField(blank=True, max_length=250, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'RandevuAdmin',
                'verbose_name_plural': 'RandevularAdmin',
                'db_table': 'appointmentAdmin',
            },
        ),
        migrations.CreateModel(
            name='appointmentCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('price', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Randevu Kategori',
                'verbose_name_plural': 'Randevu Kategori',
                'db_table': 'appointmentCategoryModel',
            },
        ),
        migrations.CreateModel(
            name='appointmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('date', models.DateField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(blank=True, default='no', max_length=200, null=True)),
                ('merchant_oid', models.CharField(blank=True, default='asd', max_length=250, null=True)),
                ('starting_time', models.TimeField(blank=True, max_length=250, null=True)),
                ('finishing_time', models.TimeField(blank=True, max_length=250, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Randevu',
                'verbose_name_plural': 'Randevular',
                'db_table': 'appointment',
            },
        ),
        migrations.CreateModel(
            name='aydinlatmaMetniModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Aydınlatma Metni',
                'verbose_name_plural': 'Aydınlatma Metni',
                'db_table': 'aydinlatmaMetniModel',
            },
        ),
        migrations.CreateModel(
            name='blogCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Blog Kategori',
                'verbose_name_plural': 'Blog Kategoriler',
                'db_table': 'BlogCategory',
            },
        ),
        migrations.CreateModel(
            name='blogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='title', unique=True)),
                ('image', models.ImageField(upload_to='blogImages')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=65, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=170, null=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Bloglar',
                'db_table': 'blogModel',
            },
        ),
        migrations.CreateModel(
            name='bottomMenuModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=150, null=True)),
                ('userType', models.CharField(blank=True, max_length=100, null=True)),
                ('menuType', models.CharField(blank=True, default='Alt Menü', max_length=100, null=True)),
                ('menuSira', models.SmallIntegerField(default=0)),
                ('meta_title', models.CharField(blank=True, max_length=65, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=170, null=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Alt Menü',
                'verbose_name_plural': 'Alt Menüler',
                'db_table': 'bottomMenuModel',
            },
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='categoryImages')),
                ('videoCount', models.PositiveSmallIntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
                'db_table': 'Kategori',
            },
        ),
        migrations.CreateModel(
            name='courseFeaturesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Kurs_Ozellikleri',
                'verbose_name_plural': 'Kurs_Ozellikleri',
                'db_table': 'Kurs_Ozellikleri',
            },
        ),
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='courseImages')),
                ('title', models.CharField(max_length=300)),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='title', unique=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('bottomDescription', ckeditor_uploader.fields.RichTextUploadingField()),
                ('videoCount', models.PositiveSmallIntegerField(default=0)),
                ('price', models.PositiveSmallIntegerField(default=0)),
                ('zoomDuration', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('average_star', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('none_average_star', models.PositiveSmallIntegerField(blank=True, default=5, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=65, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=170, null=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
                'db_table': 'Kurs',
            },
        ),
        migrations.CreateModel(
            name='courseSessionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Kurs_Bolumleri',
                'verbose_name_plural': 'Kurs_Bolumleri',
                'db_table': 'Kurs_Bolumleri',
            },
        ),
        migrations.CreateModel(
            name='courseSessionVideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('url', models.CharField(max_length=300)),
                ('minute', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('seconds', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('video_type', models.CharField(blank=True, default='everybody', max_length=300, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Kurs_Bolum_Videosu',
                'verbose_name_plural': 'Kurs_Bolum_Videolari',
                'db_table': 'Kurs_Bolum_Video',
            },
        ),
        migrations.CreateModel(
            name='footerMailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Footer Mail',
                'verbose_name_plural': 'Footer Mailler',
                'db_table': 'fotoerMail',
            },
        ),
        migrations.CreateModel(
            name='gizlilikMetniModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Gizlilik Metni',
                'verbose_name_plural': 'Gizlilik Metni',
                'db_table': 'gizlilikMetniModel',
            },
        ),
        migrations.CreateModel(
            name='hakkimizdaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hakkimizdaImages')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('description2', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Hakkımızda',
                'verbose_name_plural': 'Hakkımızda',
                'db_table': 'hakkimzida',
            },
        ),
        migrations.CreateModel(
            name='IletisimModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('subject', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('mesaj', models.TextField()),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('okundu_bilgisi', models.CharField(default='okunmadı', max_length=30)),
            ],
            options={
                'verbose_name': 'İletişim',
                'verbose_name_plural': 'İletişim',
                'db_table': 'iletisim',
            },
        ),
        migrations.CreateModel(
            name='kvkkMetniModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'KVKK Metni',
                'verbose_name_plural': 'KVKK Metni',
                'db_table': 'kvkkMetniModel',
            },
        ),
        migrations.CreateModel(
            name='LogoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(default='logo/logo.png', upload_to='logoImages')),
            ],
            options={
                'verbose_name': 'Logo Modeli',
                'verbose_name_plural': 'Logo Modelleri',
                'db_table': 'logoModel',
            },
        ),
        migrations.CreateModel(
            name='mesafeliSatisModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Mesafelili Satis',
                'verbose_name_plural': 'Mesafelili Satis',
                'db_table': 'mesafeliSatisModel',
            },
        ),
        migrations.CreateModel(
            name='PageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=65, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=170, null=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Sayfa Modeli',
                'verbose_name_plural': 'Sayfa Modelleri',
                'db_table': 'pageModel',
            },
        ),
        migrations.CreateModel(
            name='socialModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(blank=True, max_length=200, null=True)),
                ('twitter', models.CharField(blank=True, max_length=400, null=True)),
                ('pinterest', models.CharField(blank=True, max_length=200, null=True)),
                ('instagram', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Sosyal Medya',
                'verbose_name_plural': 'Sosyal Medya',
                'db_table': 'SosyalMedya',
            },
        ),
        migrations.CreateModel(
            name='topMenuModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=150, null=True)),
                ('userType', models.CharField(blank=True, max_length=100, null=True)),
                ('menuType', models.CharField(blank=True, default='Üst Menü', max_length=100, null=True)),
                ('menuSira', models.SmallIntegerField(default=0)),
                ('meta_title', models.CharField(blank=True, max_length=65, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=170, null=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Üst Menü',
                'verbose_name_plural': 'Üst Menüler',
                'db_table': 'topMenuModel',
            },
        ),
        migrations.CreateModel(
            name='whatWillYouLearnModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatWillYouLearns', to='Admin.coursemodel')),
            ],
            options={
                'verbose_name': 'Ogrenecekleriniz',
                'verbose_name_plural': 'Ogrenecekleriniz',
                'db_table': 'Ogrenecekleriniz',
            },
        ),
        migrations.CreateModel(
            name='notificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.CharField(blank=True, max_length=400, null=True)),
                ('type', models.CharField(max_length=200)),
                ('has_readen', models.CharField(default='no', max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('appointmentObject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificationsOfAppo', to='Admin.appointmentmodel')),
                ('blogObject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificationsOfBlogs', to='Admin.blogmodel')),
            ],
            options={
                'verbose_name': 'Bildirim',
                'verbose_name_plural': 'Bildirimler',
                'db_table': 'Bildirim',
            },
        ),
    ]
