# Generated by Django 4.0.3 on 2022-03-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courseImages'),
        ),
    ]
