# Generated by Django 4.0.3 on 2022-04-24 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationmodel',
            name='noti_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allNotifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificationsOfCourse', to='Admin.coursemodel'),
        ),
        migrations.AddField(
            model_name='coursesessionvideomodel',
            name='courseSession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='Admin.coursesessionmodel'),
        ),
        migrations.AddField(
            model_name='coursesessionmodel',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='Admin.coursemodel'),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userCourses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='Admin.categorymodel'),
        ),
        migrations.AddField(
            model_name='coursefeaturesmodel',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='Admin.coursemodel'),
        ),
        migrations.AddField(
            model_name='bottommenumodel',
            name='topMenu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottomMenus', to='Admin.topmenumodel'),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='categories',
            field=models.ManyToManyField(related_name='posts', to='Admin.blogcategorymodel'),
        ),
        migrations.AddField(
            model_name='appointmentmodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelssOfCategory', to='Admin.appointmentcategorymodel'),
        ),
        migrations.AddField(
            model_name='appointmentmodel',
            name='top',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bottomsAppo', to='Admin.appointmentadminmodel'),
        ),
    ]
