# Generated by Django 4.0.3 on 2022-03-15 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Admin', '0002_coursemodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userCourses', to=settings.AUTH_USER_MODEL),
        ),
    ]
