# Generated by Django 4.0.3 on 2022-05-20 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='appointmentSatisModel',
            new_name='randevuSatisModel',
        ),
        migrations.AlterModelTable(
            name='randevusatismodel',
            table='randevuSatisModel',
        ),
    ]
