# Generated by Django 4.0.3 on 2022-04-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_alter_appointmentmodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentmodel',
            name='merchant_oid',
            field=models.CharField(blank=True, default='asd', max_length=250, null=True),
        ),
    ]
