# Generated by Django 4.0.3 on 2022-04-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_appointmentmodel_merchant_oid'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentmodel',
            name='checkbox',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
