# Generated by Django 4.0.3 on 2022-03-18 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Admin', '0006_coursemodel_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='notificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('has_readen', models.CharField(default='no', max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('noti_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allNotifications', to=settings.AUTH_USER_MODEL)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificationsOfCourse', to='Admin.coursemodel')),
            ],
            options={
                'verbose_name': 'Bildirim',
                'verbose_name_plural': 'Bildirimler',
                'db_table': 'Bildirim',
            },
        ),
    ]
