# Generated by Django 4.0.3 on 2022-04-27 07:40

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_remove_appointmentmodel_checkbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointmentSatisModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Randevu Satis Bilgisi',
                'verbose_name_plural': 'Randevu Satis Bilgileri',
                'db_table': 'appointmentSatisModel',
            },
        ),
    ]
