# Generated by Django 4.0.3 on 2022-03-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_notificationmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationmodel',
            name='message',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
