# Generated by Django 4.0.3 on 2022-03-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_notificationmodel_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='meta_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='meta_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='view_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='view_pk_slug',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
