# Generated by Django 4.0.3 on 2022-03-21 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_coursemodel_meta_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemodel',
            name='view_name',
        ),
        migrations.RemoveField(
            model_name='coursemodel',
            name='view_pk_slug',
        ),
    ]
