# Generated by Django 4.0.3 on 2022-03-21 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_categorymodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='image',
            field=models.ImageField(upload_to='categoryImages'),
        ),
    ]
