# Generated by Django 4.0.3 on 2022-03-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_alter_categorymodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='average_star',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='none_average_star',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
