# Generated by Django 4.0.3 on 2022-03-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_coursemodel_average_star_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='none_average_star',
            field=models.PositiveSmallIntegerField(blank=True, default=5, null=True),
        ),
    ]
