# Generated by Django 4.0.3 on 2022-03-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0014_alter_coursemodel_none_average_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatwillyoulearnmodel',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
