# Generated by Django 4.0.3 on 2022-03-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0015_whatwillyoulearnmodel_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesessionmodel',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
