# Generated by Django 4.0.3 on 2022-03-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0016_coursesessionmodel_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(upload_to='logoImages')),
            ],
            options={
                'verbose_name': 'Logo Modeli',
                'verbose_name_plural': 'Logo Modelleri',
                'db_table': 'logoModel',
            },
        ),
    ]
