# Generated by Django 4.0.3 on 2022-03-30 11:25

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0018_alter_logomodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesessionvideomodel',
            name='video_type',
            field=models.CharField(blank=True, default='everybody', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='bottomDescription',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
