# Generated by Django 4.0.3 on 2022-04-01 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0019_coursesessionvideomodel_video_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='aydinlatmaMetniModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Aydınlatma Metni',
                'verbose_name_plural': 'Aydınlatma Metni',
                'db_table': 'aydinlatmaMetniModel',
            },
        ),
        migrations.CreateModel(
            name='gizlilikMetniModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Gizlilik Metni',
                'verbose_name_plural': 'Gizlilik Metni',
                'db_table': 'gizlilikMetniModel',
            },
        ),
        migrations.CreateModel(
            name='kvkkMetniModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'KVKK Metni',
                'verbose_name_plural': 'KVKK Metni',
                'db_table': 'kvkkMetniModel',
            },
        ),
    ]
