# Generated by Django 4.0.3 on 2022-04-01 07:43

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0020_aydinlatmametnimodel_gizlilikmetnimodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aydinlatmametnimodel',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gizlilikmetnimodel',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kvkkmetnimodel',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
