# Generated by Django 4.0.3 on 2022-04-01 10:48

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0023_blogmodel_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='title', unique=True),
        ),
    ]
