# Generated by Django 4.0.3 on 2022-04-01 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0024_blogmodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationmodel',
            name='blogObject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificationsOfBlogs', to='Admin.blogmodel'),
        ),
        migrations.AlterField(
            model_name='notificationmodel',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificationsOfCourse', to='Admin.coursemodel'),
        ),
    ]
