# Generated by Django 4.0.3 on 2022-04-01 14:39

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0025_notificationmodel_blogobject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
            ],
            options={
                'verbose_name': 'Blog Kategori',
                'verbose_name_plural': 'Blog Kategoriler',
                'db_table': 'BlogCategory',
            },
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='categories',
            field=models.ManyToManyField(related_name='posts', to='Admin.blogcategorymodel'),
        ),
    ]
