# Generated by Django 4.0.3 on 2022-04-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0028_alter_blogmodel_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategorymodel',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='blogcategorymodel',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
