# Generated by Django 4.0.3 on 2022-04-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0029_blogcategorymodel_created_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='socialModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(max_length=200)),
                ('twitter', models.CharField(blank=True, max_length=400, null=True)),
                ('pinterest', models.CharField(max_length=200)),
                ('instagram', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Sosyal Medya',
                'verbose_name_plural': 'Sosyal Medya',
                'db_table': 'SosyalMedya',
            },
        ),
    ]
