# Generated by Django 4.0.3 on 2022-04-05 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0031_alter_socialmodel_facebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iletisimmodel',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
