# Generated by Django 4.0.3 on 2022-04-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0033_mesafelisatismodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='footerMailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Footer Mail',
                'verbose_name_plural': 'Footer Mailler',
                'db_table': 'fotoerMail',
            },
        ),
    ]
