# Generated by Django 4.0.3 on 2022-04-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0034_footermailmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='minute',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='seconds',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
