# Generated by Django 4.0.3 on 2022-04-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0035_coursemodel_minute_coursemodel_seconds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemodel',
            name='minute',
        ),
        migrations.RemoveField(
            model_name='coursemodel',
            name='seconds',
        ),
        migrations.AddField(
            model_name='coursesessionvideomodel',
            name='minute',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='coursesessionvideomodel',
            name='seconds',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
