# Generated by Django 4.0.3 on 2022-04-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0038_appointmentmodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentmodel',
            name='date',
            field=models.DateField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='appointmentmodel',
            name='finishing_time',
            field=models.TimeField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='appointmentmodel',
            name='starting_time',
            field=models.TimeField(blank=True, max_length=250, null=True),
        ),
    ]
