# Generated by Django 4.0.3 on 2022-04-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0040_hakkimizdamodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hakkimizdamodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hakkimizdaImages'),
        ),
    ]
