# Generated by Django 4.0.3 on 2022-04-09 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0041_hakkimizdamodel_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentmodel',
            old_name='name',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='appointmentmodel',
            name='surname',
        ),
    ]
