# Generated by Django 4.0.3 on 2022-04-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0045_remove_appointmentadminmodel_timeduration'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentmodel',
            name='status',
            field=models.CharField(blank=True, default='no', max_length=200, null=True),
        ),
    ]
