# Generated by Django 4.0.3 on 2022-04-13 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Admin', '0047_notificationmodel_appointmentobject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmodel',
            name='noti_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allNotifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificationmodel',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
