# Generated by Django 4.0.3 on 2022-04-13 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0048_alter_notificationmodel_noti_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentmodel',
            name='top',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bottomsAppo', to='Admin.appointmentadminmodel'),
        ),
    ]
