# Generated by Django 4.0.3 on 2022-04-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0049_appointmentmodel_top'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='meta_description',
            field=models.CharField(blank=True, max_length=170, null=True),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='meta_title',
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
    ]
