# Generated by Django 4.0.3 on 2022-04-13 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0050_blogmodel_meta_description_blogmodel_meta_keywords_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagemodel',
            name='view_name',
        ),
        migrations.AddField(
            model_name='topmenumodel',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='Admin.pagemodel'),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='meta_description',
            field=models.CharField(blank=True, max_length=170, null=True),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='meta_title',
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
    ]
