# Generated by Django 4.0.3 on 2022-04-16 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0052_remove_topmenumodel_page_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointmentCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Randevu Kategori',
                'verbose_name_plural': 'Randevu Kategori',
                'db_table': 'appointmentCategoryModel',
            },
        ),
    ]
