# Generated by Django 4.0.3 on 2022-04-19 07:00

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0054_appointmentmodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='hakkimizdamodel',
            name='description2',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
