# Generated by Django 4.0.3 on 2022-04-19 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0055_hakkimizdamodel_description2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentmodel',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modelssOfCategory', to='Admin.appointmentcategorymodel'),
        ),
    ]
