# Generated by Django 4.0.3 on 2022-04-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0056_alter_appointmentmodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='zoomDuration',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
