# Generated by Django 4.0.3 on 2022-04-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0057_coursemodel_zoomduration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatwillyoulearnmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
