# Generated by Django 4.0.3 on 2022-03-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psikolog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='image',
            field=models.ImageField(default='avatar/no-avatar.png', upload_to='doctor_images'),
        ),
    ]
