# Generated by Django 4.0.3 on 2022-06-26 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psikolog', '0002_haswatchedmodel_deneme_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='haswatchedmodel',
            name='deneme_date',
        ),
    ]
