# Generated by Django 4.0.3 on 2022-03-18 09:23

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_coursemodel_slug'),
        ('psikolog', '0003_commentmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='billingCourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='billingCourseImage')),
                ('title', models.CharField(max_length=300)),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='title', unique=True)),
                ('description', models.TextField()),
                ('bottomDescription', models.TextField()),
                ('videoCount', models.PositiveSmallIntegerField(default=0)),
                ('price', models.PositiveSmallIntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userBillingCourses', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billingCourses', to='Admin.categorymodel')),
                ('payment_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paymentAllCourse', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fatura',
                'verbose_name_plural': 'Faturalar',
                'db_table': 'Fatura',
            },
        ),
    ]
