# Generated by Django 4.0.3 on 2022-03-19 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_notificationmodel_message'),
        ('psikolog', '0004_billingcoursemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingcoursemodel',
            name='category',
        ),
        migrations.AddField(
            model_name='billingcoursemodel',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billingCourses', to='Admin.coursemodel'),
        ),
    ]
