# Generated by Django 4.0.3 on 2022-03-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psikolog', '0005_remove_billingcoursemodel_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='sliderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sliderImages')),
                ('top_title', models.CharField(max_length=300)),
                ('bottom_title', models.CharField(max_length=300)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Sliderlar',
                'db_table': 'Slider',
            },
        ),
    ]
