# Generated by Django 4.0.3 on 2022-03-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psikolog', '0006_slidermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidermodel',
            name='sira',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
