# Generated by Django 4.0.3 on 2022-03-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psikolog', '0007_slidermodel_sira'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='image',
            field=models.ImageField(default='avatar/no-avatar.png', upload_to='profile_images'),
        ),
    ]
