# Generated by Django 4.0.3 on 2022-03-26 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0014_alter_coursemodel_none_average_star'),
        ('psikolog', '0009_billingcoursemodel_average_star_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='favouriteCourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.coursemodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favouriteCourses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favori Kurs',
                'verbose_name_plural': 'Favori Kurslar',
                'db_table': 'Favori_Kurslar',
            },
        ),
    ]
