# Generated by Django 4.0.3 on 2022-04-01 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0024_blogmodel_slug'),
        ('psikolog', '0010_favouritecoursemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_comments', to='Admin.blogmodel'),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_comments', to='Admin.coursemodel'),
        ),
    ]
