# Generated by Django 4.0.3 on 2022-04-05 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0032_alter_iletisimmodel_subject'),
        ('psikolog', '0011_commentmodel_blog_alter_commentmodel_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
                ('merchant_oid', models.CharField(max_length=250)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.coursemodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderCourses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Siparis',
                'verbose_name_plural': 'Siparisler',
                'db_table': 'siparis',
            },
        ),
    ]
