# Generated by Django 4.0.3 on 2022-04-05 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psikolog', '0012_ordermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
