# Generated by Django 4.0.3 on 2022-04-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psikolog', '0013_ordermodel_created_date_ordermodel_updated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='price',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
