# Generated by Django 4.0.3 on 2022-04-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psikolog', '0014_ordermodel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='hash',
            field=models.CharField(blank=True, max_length=750, null=True),
        ),
    ]
