# Generated by Django 4.0.3 on 2022-04-08 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psikolog', '0015_ordermodel_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='hash',
        ),
    ]
