# Generated by Django 4.0.3 on 2022-04-10 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0042_rename_name_appointmentmodel_fullname_and_more'),
        ('psikolog', '0016_remove_ordermodel_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='hasWatchedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchedVideos', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.coursesessionvideomodel')),
            ],
            options={
                'verbose_name': 'İzlenen Video',
                'verbose_name_plural': 'İzlenen Videolar',
                'db_table': 'watchedVideos',
            },
        ),
    ]
